spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE}

  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: ${HANA_URL}
    username: ${HANA_DATASOURCE_USERNAME}
    password: ${HANA_DATASOURCE_PASSWORD}


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091