server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: User-Interface
              uri: lb://User-Interface
              predicates:
                - Path=/ai-agent/** , /auth/**

            - id: Car-Booking-MS
              uri: lb://Car-Booking-MS
              predicates:
                - Path=/car-booking/**
              filters:
                - name: AuthFilter

            - id: CAR-DETAILS-MS
              uri: lb://CAR-DETAILS-MS
              predicates:
                - Path=/car-detail/admin/**
              filters:
                - name: AuthFilter

            - id: CAR-DETAILS-MS-PUBLIC
              uri: lb://CAR-DETAILS-MS
              predicates:
                - Path=/public/**

jwtKey: ${JWT}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka