server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: User-Interface
              uri: lb://User-Interface
              predicates:
                - Path=/ai-agent/** , /auth/**

            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotel/**
              filters:
                - name: AuthFilter

            - id: RATING-SERVICE
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/rating/**
              filters:
                - name: AuthFilter

jwtKey: ${JWT}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka